### ISSUE TITLE
 Width/Height in Latest Information

### ISSUE THREAD

**Issue by mmojadad** [optimlab/optimblog#10] opened 2020-05-26 12:28 UTC
I am using BigShop Theme
Demo ( http://demo.harnishdesign.net/opencart/bigshop/v1/index.php?route=common/home )
In OptimBlog : Latest Information , When i change Width/Height , Nothing change in frontend.
I noticed if in my css theme change col-lg-3 from %25 to for example %35 it will show good.

**Comment by optimlab** [comment] 2020-05-26 12:36
Duplicate of #5

**Closed as completed by optimlab** 2020-05-26 12:36 UTC
Labels: duplicate
